Updates for Rake
```
ERROR: 'rake/gempackagetask' is obsolete and no longer supported. Use
'rubygems/package_task' instead.
/Users/acid/src/net-denon-gem/tasks/gem.rake:3:in `<top (required)>'
/Users/acid/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in
`eval'
/Users/acid/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in
`<main>'
(See full trace by running task with --trace)
```