Update for Rake
```
ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use
'rdoc/task' (available in RDoc 2.4.2+) instead.
/Users/acid/src/net-denon-gem/tasks/rdoc.rake:3:in `<top (required)>'
/Users/acid/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in
`eval'
/Users/acid/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in
`<main>'
(See full trace by running task with --trace)
```